wip

diff --git a/waspc/run b/waspc/run
--- a/waspc/run
+++ b/waspc/run
@@ -17,6 +17,7 @@ GREEN="\033[32m"
 RED="\033[31m"
 DEFAULT_COLOR="\033[39m"
 
+# Building
 WASP_PACKAGES_COMPILE="${SCRIPT_DIR}/tools/install_packages_to_data_dir.sh"
 BUILD_HS_CMD="cabal build all"
 BUILD_HS_FULL_CMD="cabal build all --enable-tests --enable-benchmarks"
@@ -25,20 +26,33 @@ BUILD_ALL_STATIC_CMD="$WASP_PACKAGES_COMPILE && $BUILD_HS_CMD --enable-executabl
 
 INSTALL_CMD="$WASP_PACKAGES_COMPILE && cabal install --overwrite-policy=always"
 
-TEST_UNIT_CMD="cabal test waspc-test"
-TEST_CLI_CMD="cabal test cli-test"
-TEST_SNAPSHOT_CMD="cabal test snapshot-tests"
-TEST_SNAPSHOT_DELETE_GOLDENS="rm -rf $PROJECT_ROOT/snapshot-tests/test-outputs/*-golden"
-TEST_SNAPSHOT_ACCEPT_ALL_CMD="$TEST_SNAPSHOT_DELETE_GOLDENS && $TEST_SNAPSHOT_CMD"
-TEST_HEADLESS_CMD="cd $PROJECT_ROOT/examples/todoApp && npm install && npm run test"
-TEST_CMD="cabal test && echo 'Running headless tests' && $TEST_HEADLESS_CMD && echo 'ALL TESTS PASSED' || { echo 'SOME TESTS FAILED'; exit 1; }"
+# Testing
+WASPC_UNIT_TEST_CMD="cabal test waspc-tests"
 
+WASP_CLI_UNIT_TEST_CMD="cabal test cli-unit-tests"
+WASP_CLI_E2E_TEST_CMD="cabal test cli-e2e-tests"
+WASP_CLI_E2E_TEST_DELETE_GOLDENS="rm -rf $PROJECT_ROOT/cli-e2e-tests/test-outputs/*-golden"
+WASP_CLI_E2E_TEST_ACCEPT_CURRENT_CMD="$WASP_CLI_E2E_TEST_DELETE_GOLDENS && $WASP_CLI_E2E_TEST_CMD"
+WASP_CLI_TEST_CMD="$WASP_CLI_UNIT_TEST_CMD && $WASP_CLI_E2E_TEST_CMD"
+
+TODO_APP_E2E_TEST_CMD="cd $PROJECT_ROOT/examples/todoApp && npm install && npm run test"
+
+STARTERS_E2E_TEST_CMD="cd $PROJECT_ROOT/waspc/starters-e2e-tests && npm install && npm run test:dev"
+
+TEST_CMD="cabal test && \
+  echo 'Running e2e tests' && \
+  $TODO_APP_E2E_TEST_CMD && \
+  $STARTERS_E2E_TEST_CMD && \
+  echo 'ALL TESTS PASSED' || \
+  { echo 'SOME TESTS FAILED'; exit 1; }"
+
+# Running
 RUN_CMD="cabal --project-dir=${PROJECT_ROOT} run wasp-cli -- ${ARGS[@]}"
-GHCID_CMD="ghcid --command=cabal repl"
 
+# Utility
+GHCID_CMD="ghcid --command=cabal repl"
 # ghc version below should be the one from `cabal.project` file, `with-compiler` field.
 GHCUP_SET="ghcup set ghc 8.10.7 && ghcup set hls 2.2.0.0"
-
 DEV_TOOLS_BIN="$PROJECT_ROOT/.bin"
 function install_dev_tool() {
   echo "cabal --project-file=$PROJECT_ROOT/dev-tool.project install $1 --installdir=$DEV_TOOLS_BIN --install-method=copy --overwrite-policy=always"
@@ -90,17 +104,21 @@ print_usage() {
     "Installs the wasp executable as 'wasp-cli' globally on the machine."
   echo ""
   print_usage_cmd "test" \
-    "Executes all tests (unit + e2e snapshot + e2e headless). Builds the project first if needed."
-  print_usage_cmd "test:unit [pattern]" \
-    "Executes only unit tests. Builds the project first if needed. If pattern is provided, it will run only tests whose description/name matches the pattern. Check https://github.com/UnkindPartition/tasty#patterns to learn more about valid patterns."
+    "Executes all tests (waspc + Wasp CLI + todoApp + starters). Builds the project first if needed."
+  print_usage_cmd "test:waspc:unit [pattern]" \
+    "Executes only waspc unit tests. Builds the project first if needed. If pattern is provided, it will run only tests whose description/name matches the pattern. Check https://github.com/UnkindPartition/tasty#patterns to learn more about valid patterns."
   print_usage_cmd "test:cli" \
+    "Executes only cli tests. Builds the project first if needed."
+  print_usage_cmd "test:cli:unit" \
     "Executes only cli unit tests. Builds the project first if needed."
-  print_usage_cmd "test:snapshot" \
-    "Executes only snapshot tests. Builds the project first if needed."
-  print_usage_cmd "test:snapshot:accept-all" \
-    "Accepts any diffs in the generated code in snapshot tests. Does so by deleting current golden output and re-running snapshot tests to produce new golden output."
-  print_usage_cmd "test:headless" \
-    "Executes e2e headless tests, where example wasp apps are tested using Playwright."
+  print_usage_cmd "test:cli:e2e" \
+    "Executes only cli e2e tests. Builds the project first if needed."
+  print_usage_cmd "test:cli:e2e:accept-all" \
+    "Accepts any diffs in the generated code in Wasp CLI snapshot tests. Does so by deleting the current golden output and re-running snapshot tests to produce the new golden output."
+  print_usage_cmd "test:todoApp" \
+    "Executes only todoApp e2e tests. Installs deps first if needed."
+  print_usage_cmd "test:starters" \
+    "Executes only starters e2e tests. Installs deps first if needed."
   echo ""
   print_usage_cmd "ghcid" \
     "Runs ghcid, which watches source file changes and reports errors. Does not watch tests."
@@ -147,11 +165,9 @@ case $COMMAND in
   build:packages)
     echo_and_eval "$WASP_PACKAGES_COMPILE"
     ;;
-
   install)
     echo_and_eval "$INSTALL_CMD"
     ;;
-
   ghcid)
     echo_and_eval "$GHCID_CMD"
     ;;
@@ -161,36 +177,38 @@ case $COMMAND in
     #   around :main --color always that way and it was not working.
     ghcid -T=':main --color always' --command=cabal repl test/TastyDiscoverDriver.hs
     ;;
-
   test)
     echo_and_eval "$TEST_CMD"
     ;;
-  test:unit)
+  test:waspc:unit)
     TEST_PATTERN="${ARGS[0]}"
     if [[ -z "$TEST_PATTERN" ]]; then
-      echo_and_eval "$TEST_UNIT_CMD"
+      echo_and_eval "$WASPC_UNIT_TEST_CMD"
     else
-      echo_and_eval "$TEST_UNIT_CMD --test-options \"-p \\\"$TEST_PATTERN\\\"\""
+      echo_and_eval "$WASPC_UNIT_TEST_CMD --test-options \"-p \\\"$TEST_PATTERN\\\"\""
     fi
-
     ;;
   test:cli)
-    echo_and_eval "$TEST_CLI_CMD"
+    echo_and_eval "$WASP_CLI_TEST_CMD"
     ;;
-  test:snapshot)
-    echo_and_eval "$TEST_SNAPSHOT_CMD"
+  test:cli:unit)
+    echo_and_eval "$WASP_CLI_UNIT_TEST_CMD"
     ;;
-  test:snapshot:accept-all)
-    echo_and_eval "$TEST_SNAPSHOT_ACCEPT_ALL_CMD"
+  test:cli:e2e)
+    echo_and_eval "$WASP_CLI_E2E_TEST_CMD"
     ;;
-  test:headless)
-    echo_and_eval "$TEST_HEADLESS_CMD"
+  test:cli:e2e:accept-all)
+    echo_and_eval "$WASP_CLI_E2E_TEST_ACCEPT_CURRENT_CMD"
     ;;
-
+  test:todoApp)
+    echo_and_eval "$TODO_APP_E2E_TEST_CMD"
+    ;;
+  test:starters)
+    echo_and_eval "$STARTERS_E2E_TEST_CMD"
+    ;;
   wasp-cli)
     echo_and_eval "$RUN_CMD"
     ;;
-
   stan)
     echo_and_eval "$STAN_CMD"
     ;;
@@ -245,7 +263,6 @@ case $COMMAND in
   module-graph)
     echo_and_eval "graphmod --quiet --prune-edges $PROJECT_ROOT/src/**/*.hs | dot -Gsize=60,60! -Tpng -o module-graph.png" && echo "Printed module graph to module-graph.png."
     ;;
-
   ghcup-set)
     echo_and_eval "$GHCUP_SET"
     ;;
