Revert "debug"
This reverts commit 6028ef55221deed2c384536eed77dff6c35f25c5.

diff --git a/.github/workflows/ci-deploy-test.yaml b/.github/workflows/ci-deploy-test.yaml
--- a/.github/workflows/ci-deploy-test.yaml
+++ b/.github/workflows/ci-deploy-test.yaml
@@ -22,6 +22,89 @@ env:
   RAILWAY_WASP_WORKSPACE_ID: ${{ secrets.RAILWAY_WASP_WORKSPACE_ID }}
 
 jobs:
+  test_fly_deployment:
+    name: Test Fly deployment
+    runs-on: ubuntu-latest
+    environment:
+      name: fly-deploy-test
+
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+      - uses: ./.github/actions/setup-tools
+
+      - uses: ./.github/actions/install-wasp-cli-artifact
+
+      - name: Install app dependencies
+        working-directory: ${{ env.APP_TO_DEPLOY }}
+        run: wasp-cli install
+
+      - name: Install Fly CLI
+        # NOTE: We tell users to install the latest version of Fly CLI,
+        # so we use it here too.
+        uses: superfly/flyctl-actions/setup-flyctl@v1
+
+      - name: Deploy app to Fly
+        working-directory: ${{ env.APP_TO_DEPLOY }}
+        run: |
+          # `fly launch` fails if Fly toml files already exist.
+          rm -f fly-server.toml fly-client.toml
+
+          echo "Deploying with prefix: $APP_PREFIX"
+          mapfile -d $'\0' -t ENV_VAR_ARGUMENTS < <(node ../../scripts/deploy-test/prepare-deploy-secrets.mjs .env.server.example)
+          # NOTE:
+          # - The `yes` command is necessary because the `fly launch` command
+          # prompts for confirmation.
+          # - We use a Bash array for `$ENV_VAR_ARGUMENTS` to ensure proper
+          # word splitting (i.e., force Bash to interpret the flags separately
+          # instead of passing it as a single string value).
+          yes | wasp-cli deploy fly launch "$APP_PREFIX" "$FLY_REGION" --org "$FLY_ORG" "${ENV_VAR_ARGUMENTS[@]}"
+
+      - name: Get deployed app hostnames
+        id: get-hostnames
+        working-directory: ${{ env.APP_TO_DEPLOY }}
+        run: |
+          function get_fly_app_hostname() {
+            config_file="$1"
+            flyctl status -j -c "$config_file" | jq -r '.Hostname'
+          }
+          SERVER_HOSTNAME=$(get_fly_app_hostname fly-server.toml)
+          CLIENT_HOSTNAME=$(get_fly_app_hostname fly-client.toml)
+          echo "server=$SERVER_HOSTNAME" >> "$GITHUB_OUTPUT"
+          echo "client=$CLIENT_HOSTNAME" >> "$GITHUB_OUTPUT"
+
+      - name: Run E2E tests against deployed app
+        working-directory: ${{ env.APP_TO_DEPLOY }}
+        env:
+          WASP_RUN_MODE: deployed
+          PLAYWRIGHT_BASE_URL: "https://${{ steps.get-hostnames.outputs.client }}"
+          PLAYWRIGHT_SERVER_URL: "https://${{ steps.get-hostnames.outputs.server }}"
+        run: npm test
+
+  cleanup_fly_deploy_test:
+    name: Clean up Fly deployment test apps
+    runs-on: ubuntu-latest
+    needs: test_fly_deployment
+    # NOTE: Fly deployments can sometimes "fail" but still deploy the apps. We
+    # want to always clean them up.
+    if: always()
+
+    steps:
+      - uses: superfly/flyctl-actions/setup-flyctl@v1
+        with:
+          # NOTE: We pinned the Fly version because we don't want the changes in the
+          # Fly CLI to affect our cleanup procedure. `fly destroy` isn't a part
+          # of Wasp, we're just incidentally using the same tool Wasp uses.
+          version: v0.3.164
+
+      - name: Clean up test apps
+        run: |
+          # NOTE: We are relying on Wasp's naming conventions here
+          flyctl apps destroy -y $APP_PREFIX-server || true
+          flyctl apps destroy -y $APP_PREFIX-client || true
+          flyctl apps destroy -y $APP_PREFIX-db || true
+
   test_railway_deployment:
     name: Test Railway deployment
     runs-on: ubuntu-latest
@@ -57,10 +140,6 @@ jobs:
           # word splitting (i.e., force Bash to interpret the flags separately
           # instead of passing it as a single string value).
           wasp-cli deploy railway launch "$APP_PREFIX" --workspace $RAILWAY_WASP_WORKSPACE_ID "${ENV_VAR_ARGUMENTS[@]}"
-
-      - name: DEBUG
-        run: |
-          railway status --json
 
       - name: Get deployed app hostnames
         id: get-hostnames
